import type { RouteType } from "@/lib/types";

export type SeedTrailRow = {
  id: string;
  name: string;
  lat: number;
  lng: number;
  region: string;
  distanceKm: number;
  elevationGainM: number;
  maxAltitudeM?: number;
  routeType: RouteType;
  technicalScore: number;
  exposureScore: number;
  generalRating?: number;
  wildlifeRating?: number;
  /** Reach trailhead on foot from a typical town/base without driving (long walk OK). */
  accessWalking: boolean;
  accessTransit: boolean;
  accessCar: boolean;
  transitNotes?: string;
};

const clamp = (value: number, min: number, max: number) =>
  Math.max(min, Math.min(max, value));

export function computePhysicalScore(distanceKm: number, elevationGainM: number): number {
  const score = distanceKm / 4 + elevationGainM / 220;
  return clamp(Math.round(score), 1, 5);
}

export const seedTrailRows: SeedTrailRow[] = [
  {
    id: "johnston-canyon",
    name: "Johnston Canyon to Ink Pots",
    lat: 51.2442,
    lng: -115.8398,
    region: "banff_canmore",
    distanceKm: 11.7,
    elevationGainM: 360,
    routeType: "out_and_back",
    technicalScore: 2,
    exposureScore: 1,
    generalRating: 4.6,
    wildlifeRating: 3.4,
    accessWalking: false,
    accessTransit: true,
    accessCar: true,
    transitNotes: "Roam Route 9 to Johnston Canyon stop in peak season.",
  },
  {
    id: "sulphur-mountain",
    name: "Sulphur Mountain Trail",
    lat: 51.1437,
    lng: -115.5717,
    region: "banff_canmore",
    distanceKm: 10.8,
    elevationGainM: 760,
    routeType: "out_and_back",
    technicalScore: 2,
    exposureScore: 2,
    generalRating: 4.4,
    wildlifeRating: 2.9,
    accessWalking: true,
    accessTransit: true,
    accessCar: true,
    transitNotes: "Walkable from Banff town or use local Roam bus.",
  },
  {
    id: "ha-ling",
    name: "Ha Ling Peak",
    lat: 51.0569,
    lng: -115.3333,
    region: "banff_canmore",
    distanceKm: 7.4,
    elevationGainM: 760,
    routeType: "out_and_back",
    technicalScore: 3,
    exposureScore: 4,
    generalRating: 4.8,
    wildlifeRating: 3.1,
    accessWalking: false,
    accessTransit: true,
    accessCar: true,
    transitNotes: "Transit + short ride-share often needed from Canmore center.",
  },
  {
    id: "tunnel-mountain",
    name: "Tunnel Mountain Summit",
    lat: 51.1786,
    lng: -115.5551,
    region: "banff_canmore",
    distanceKm: 4.6,
    elevationGainM: 290,
    routeType: "out_and_back",
    technicalScore: 1,
    exposureScore: 1,
    generalRating: 4.3,
    wildlifeRating: 2.5,
    accessWalking: true,
    accessTransit: true,
    accessCar: true,
    transitNotes: "Directly reachable on foot from Banff downtown.",
  },
  {
    id: "plain-of-six-glaciers",
    name: "Plain of Six Glaciers",
    lat: 51.4123,
    lng: -116.2187,
    region: "banff_canmore",
    distanceKm: 13.9,
    elevationGainM: 590,
    routeType: "out_and_back",
    technicalScore: 2,
    exposureScore: 3,
    generalRating: 4.9,
    wildlifeRating: 3.9,
    accessWalking: false,
    accessTransit: true,
    accessCar: true,
    transitNotes: "Roam Route 8X to Lake Louise in summer.",
  },
  {
    id: "vermilion-lakes",
    name: "Vermilion Lakes",
    lat: 51.1675,
    lng: -115.575,
    region: "banff_canmore",
    distanceKm: 4.8,
    elevationGainM: 80,
    routeType: "loop",
    technicalScore: 1,
    exposureScore: 1,
    generalRating: 4.2,
    wildlifeRating: 3.0,
    accessWalking: true,
    accessTransit: true,
    accessCar: true,
    transitNotes: "Short walk or bike from Banff town; Roam bus nearby.",
  },
  {
    id: "grassi-lakes",
    name: "Grassi Lakes",
    lat: 51.0515,
    lng: -115.375,
    region: "banff_canmore",
    distanceKm: 3.8,
    elevationGainM: 240,
    routeType: "out_and_back",
    technicalScore: 1,
    exposureScore: 2,
    generalRating: 4.5,
    wildlifeRating: 2.2,
    accessWalking: true,
    accessTransit: true,
    accessCar: true,
    transitNotes: "Walkable from Canmore; local bus in season.",
  },
  {
    id: "lake-agnes",
    name: "Lake Agnes Teahouse",
    lat: 51.4138,
    lng: -116.281,
    region: "banff_canmore",
    distanceKm: 7.6,
    elevationGainM: 400,
    routeType: "out_and_back",
    technicalScore: 2,
    exposureScore: 2,
    generalRating: 4.7,
    wildlifeRating: 3.5,
    accessWalking: false,
    accessTransit: true,
    accessCar: true,
    transitNotes: "Shuttle to Lake Louise lakefront, then hike from shore.",
  },
  {
    id: "consolation-lakes",
    name: "Consolation Lakes",
    lat: 51.3765,
    lng: -116.2555,
    region: "banff_canmore",
    distanceKm: 12.6,
    elevationGainM: 255,
    routeType: "out_and_back",
    technicalScore: 2,
    exposureScore: 2,
    generalRating: 4.6,
    wildlifeRating: 3.8,
    accessWalking: false,
    accessTransit: true,
    accessCar: true,
    transitNotes: "Moraine Lake shuttle in season; check Parks Canada access.",
  },
  {
    id: "moraine-lakeshore",
    name: "Moraine Lake Lakeshore",
    lat: 51.3285,
    lng: -116.181,
    region: "banff_canmore",
    distanceKm: 2.9,
    elevationGainM: 65,
    routeType: "out_and_back",
    technicalScore: 1,
    exposureScore: 1,
    generalRating: 4.8,
    wildlifeRating: 3.2,
    accessWalking: false,
    accessTransit: true,
    accessCar: true,
    transitNotes: "Moraine Lake shuttle; flat lakeshore walk.",
  },
  {
    id: "bow-river-loop",
    name: "Bow River Loop (Banff)",
    lat: 51.178,
    lng: -115.572,
    region: "banff_canmore",
    distanceKm: 6.4,
    elevationGainM: 120,
    routeType: "loop",
    technicalScore: 1,
    exposureScore: 1,
    generalRating: 4.1,
    wildlifeRating: 2.8,
    accessWalking: true,
    accessTransit: true,
    accessCar: true,
    transitNotes: "Starts near Banff town centre; Roam-friendly.",
  },
  {
    id: "hoodoos-trail",
    name: "Banff Hoodoos Trail",
    lat: 51.1805,
    lng: -115.548,
    region: "banff_canmore",
    distanceKm: 10.2,
    elevationGainM: 310,
    routeType: "out_and_back",
    technicalScore: 1,
    exposureScore: 2,
    generalRating: 4.0,
    wildlifeRating: 3.0,
    accessWalking: true,
    accessTransit: true,
    accessCar: true,
    transitNotes: "Reachable on foot from Banff; partial Roam access.",
  },
  {
    id: "peyto-lake-viewpoint",
    name: "Peyto Lake Viewpoint (Bow Summit)",
    lat: 51.7185,
    lng: -116.1425,
    region: "banff_canmore",
    distanceKm: 2.5,
    elevationGainM: 95,
    routeType: "out_and_back",
    technicalScore: 1,
    exposureScore: 2,
    generalRating: 4.7,
    wildlifeRating: 2.5,
    accessWalking: false,
    accessTransit: false,
    accessCar: true,
    transitNotes: "Icefields Parkway — day trip by car from Banff/Lake Louise.",
  },
  {
    id: "johnson-lake",
    name: "Johnson Lake",
    lat: 51.214,
    lng: -115.532,
    region: "banff_canmore",
    distanceKm: 3.0,
    elevationGainM: 45,
    routeType: "loop",
    technicalScore: 1,
    exposureScore: 1,
    generalRating: 4.3,
    wildlifeRating: 3.2,
    accessWalking: false,
    accessTransit: true,
    accessCar: true,
    transitNotes: "Roam Route 6 toward Minnewanka road; short lakeside loop.",
  },
  {
    id: "cory-pass",
    name: "Cory Pass Loop",
    lat: 51.223,
    lng: -115.561,
    region: "banff_canmore",
    distanceKm: 13.0,
    elevationGainM: 915,
    routeType: "loop",
    technicalScore: 4,
    exposureScore: 4,
    generalRating: 4.5,
    wildlifeRating: 3.0,
    accessWalking: false,
    accessTransit: true,
    accessCar: true,
    transitNotes: "Transit to Banff then taxi/shuttle to trailhead area.",
  },
];
